-- Eliminacion de objetos preexistentes

IF OBJECT_ID('SPARK.DIM_CLIENTE','U') IS NOT NULL
  DROP TABLE SPARK.DETALLE_FACTURA;

IF OBJECT_ID (N'SPARK.GetAge', N'FN') IS NOT NULL  
    DROP FUNCTION getAge;


-- Creacion de las tablas

CREATE TABLE SPARK.DIM_CLIENTE (
CLIENTE_ID INT IDENTITY(1,1) PRIMARY KEY,
CLIENTE_DNI DECIMAL(18,0), 
CLIENTE_APELLIDO NVARCHAR(255) NOT NULL, 
CLIENTE_NOMBRE NVARCHAR(255) NOT NULL,  
CLIENTE_EDAD NVARCHAR(255) NOT NULL);


-- Migracion

-- DIM_CLIENTE

INSERT SPARK.DIM_CLIENTE
SELECT CLIENTE_ID, 
		CLIENTE_DNI,
		CLIENTE_APELLIDO,
		CLIENTE_NOMBRE,
		CASE 
		WHEN SPARK.GetAge(CLIENTE_FECHA_NACIMIENTO) BETWEEN 18 AND 30 THEN '[18-30]'
		WHEN SPARK.GetAge(CLIENTE_FECHA_NACIMIENTO) BETWEEN 31 AND 50 THEN '[31-50]'
		WHEN SPARK.GetAge(CLIENTE_FECHA_NACIMIENTO) > 50 THEN '>50'
		END AS CLIENTE_EDAD
FROM SPARK.CLIENTE



-- Funciones

CREATE FUNCTION SPARK.GetAge(@Fecha nvarchar(255))
RETURNS decimal(3,0)
AS
BEGIN
	DECLARE @Edad decimal(3,0)
	SELECT @Edad = year(CURRENT_TIMESTAMP) - SUBSTRING(@Fecha, 1, 4)

	RETURN @Edad
END;
GO